### ISSUE TITLE
S3 is here

### ISSUE THREAD

**Issue by ghost** [rolandoislas/rick-bot-number-3#1]
Today season 3 was released, so messages like "Season three is about 3 months, 28 days, 14 hours, 34 minutes, 24 seconds away. Summer (assuming August) 2017" make no sense. Maybe make a timer for the next episode, or facts about s3

**Comment by opencma** [comment]
I am going off of this [tweet](https://twitter.com/RickandMorty/status/848430417233313792).

However, to avoid confusion I will modify the message to be "**More** season three in about...".
